export const FETCH_SECURITY_QUESTIONS = 'FETCH_SECURITY_QUESTIONS';
export const FILTER_SECURITY_QUESTIONS = 'FILTER_SECURITY_QUESTIONS';
export const FILTER_SECURITY_QUESTION_ONE = 'FILTER_SECURITY_QUESTION_ONE';
export const FILTER_SECURITY_QUESTION_TWO = 'FILTER_SECURITY_QUESTION_TWO';

export const USER_BASIC_DATA_EVENT_HANDLER = 'USER_BASIC_DATA_EVENT_HANDLER';
export const PASSWORD_EVENT_HANDLER = 'PASSWORD_EVENT_HANDLER';
export const GENDER_EVENT_HANDLER = 'GENDER_EVENT_HANDLER';
export const MARITAL_STATUS_EVENT_HANDLER = 'MARITAL_STATUS_EVENT_HANDLER';
export const SECURITY_ANSWER_ONE = 'SECURITY_ANSWER_ONE';
export const SECURITY_ANSWER_TWO = 'SECURITY_ANSWER_TWO';

export const SET_USER_ID = 'SET_USER_ID';

